### ISSUE TITLE
Related Work

### ISSUE THREAD

**Issue by SivilTaram** [verypluming/SyGNS#1]
Dear authors,

Congratulations on your paper "SyGNS: A Systematic Generalization Testbed Based on Natural Language Semantics" accepted by ACL 2021! It is very interesting and the conclusion is insightful for me! You may be also interested in our EMNLP 2020 paper [Benchmarking Meaning Representations in Neural Semantic Parsing](https://www.aclweb.org/anthology/2020.emnlp-main.118.pdf) and NeurIPS 2020 paper [Compositional Generalization by Learning Analytical Expressions](https://proceedings.neurips.cc//paper/2020/file/83adc9225e4deb67d7ce42d58fe5157c-Paper.pdf). 

The former paper studies the performance difference among several meaning representations in semantic parsing, while your paper studies from another refreshing view - compositional generalizaiton, which I personally very love! The latter one designs a general architecture for "perfect" generalization capability of current DNN models. We may have a discussion during the ACL conference if there is a chance. Feel free to close the issue 😄 

Best Regards,
Qian

**Comment by verypluming** [comment]
Dear Qian,

Thanks for your message!
I am very glad to know that you are also working on analyzing neural networks on semantic parsing tasks.
We will check your papers in detail later.
Thanks again!

Best,
Hitomi
